/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/ButtonWithLabel`; params?: Router.UnknownInputParams; } | { pathname: `/components/InputWithLabel`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/RestaurantScreen`; params?: Router.UnknownInputParams; } | { pathname: `/utils/routes`; params?: Router.UnknownInputParams; } | { pathname: `/utils/colors`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ButtonWithLabel`; params?: Router.UnknownOutputParams; } | { pathname: `/components/InputWithLabel`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/AppNavigator`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/RestaurantScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/routes`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/colors`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/ButtonWithLabel${`?${string}` | `#${string}` | ''}` | `/components/InputWithLabel${`?${string}` | `#${string}` | ''}` | `/navigation/AppNavigator${`?${string}` | `#${string}` | ''}` | `/screens/HomeScreen${`?${string}` | `#${string}` | ''}` | `/screens/RestaurantScreen${`?${string}` | `#${string}` | ''}` | `/utils/routes${`?${string}` | `#${string}` | ''}` | `/utils/colors${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/ButtonWithLabel`; params?: Router.UnknownInputParams; } | { pathname: `/components/InputWithLabel`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/RestaurantScreen`; params?: Router.UnknownInputParams; } | { pathname: `/utils/routes`; params?: Router.UnknownInputParams; } | { pathname: `/utils/colors`; params?: Router.UnknownInputParams; };
    }
  }
}
